#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for locator/repartitioning
#
# IDENTIFICATION
#    src/backend/locator/repartitioning/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/locator/partitioning
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	locator_partitioning.o \
	locator_partitioning_delta.o \
	locator_external_catalog.o \
	locator_external_catalog_hash.o \
	locator_external_catalog_file.o \
	locator_external_catalog_utils.o

include $(top_srcdir)/src/backend/common.mk
